protected/models/Subbagian.php
<?php

/**
 * This is the model class for table "tmsubbagian".
 *
 * The followings are the available columns in table 'tmsubbagian':
 * @property string $subbagianid
 * @property string $bagianid
 * @property string $kode
 * @property string $nama
 * @property string $alamat
 * @property string $keterangan
 * @property string $tahun
 * @property string $opadd
 * @property string $tgladd
 * @property string $pcadd
 * @property string $opedit
 * @property string $tgledit
 * @property string $pcedit
 * @property integer $dlt
 *
 * The followings are the available model relations:
 * @property Tmjabatan[] $tmjabatans
 * @property Tmbagian $bagian
 * @property Ttsuratmasuk[] $ttsuratmasuks
 */
class Subbagian extends CActiveRecord
{
	public $bagiannama="";
	public $bagiankode="";
	/**
	 * Returns the static model of the specified AR class.
	 * @return Subbagian the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'tmsubbagian';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('subbagianid', 'required'),
			array('dlt', 'numerical', 'integerOnly'=>true),
			array('subbagianid, bagianid, kode', 'length', 'max'=>20),
			array('nama, alamat, keterangan', 'length', 'max'=>254),
			array('tahun', 'length', 'max'=>4),
			array('opadd, pcadd, opedit, pcedit', 'length', 'max'=>40),
			array('tgladd, tgledit', 'safe'),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('subbagianid, bagianid, kode, nama, alamat, keterangan, tahun, opadd, tgladd, pcadd, opedit, tgledit, pcedit, dlt', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'tmjabatans' => array(self::HAS_MANY, 'Tmjabatan', 'subbagianid'),
			'bagian' => array(self::BELONGS_TO, 'Tmbagian', 'bagianid'),
			'ttsuratmasuks' => array(self::HAS_MANY, 'Ttsuratmasuk', 'subbagianid'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'subbagianid' => 'Subbagianid',
			'bagianid' => 'Bagianid',
			'kode' => 'Kode',
			'nama' => 'Nama',
			'alamat' => 'Alamat',
			'keterangan' => 'Keterangan',
			'tahun' => 'Tahun',
			'opadd' => 'Opadd',
			'tgladd' => 'Tgladd',
			'pcadd' => 'Pcadd',
			'opedit' => 'Opedit',
			'tgledit' => 'Tgledit',
			'pcedit' => 'Pcedit',
			'dlt' => 'Dlt',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('subbagianid',$this->subbagianid,true);
		$criteria->compare('bagianid',$this->bagianid,true);
		$criteria->compare('kode',$this->kode,true);
		$criteria->compare('nama',$this->nama,true);
		$criteria->compare('alamat',$this->alamat,true);
		$criteria->compare('keterangan',$this->keterangan,true);
		$criteria->compare('tahun',$this->tahun,true);
		$criteria->compare('opadd',$this->opadd,true);
		$criteria->compare('tgladd',$this->tgladd,true);
		$criteria->compare('pcadd',$this->pcadd,true);
		$criteria->compare('opedit',$this->opedit,true);
		$criteria->compare('tgledit',$this->tgledit,true);
		$criteria->compare('pcedit',$this->pcedit,true);
		$criteria->compare('dlt',$this->dlt);

		return new CActiveDataProvider(get_class($this), array(
			'criteria'=>$criteria,
		));
	}
}

protected/controllers/SubbagianController.php
<?php

class SubbagianController extends Controller {

    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/column2';

    /**
     * @return array action filters
     */
    public function filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
            'postOnly + delete', // we only allow deletion via POST request
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules() {
        return array(
            array('allow',
                'actions' => array('admin', 'view','loadbagian'),
                'expression' => '$user->getprivileges(\'view\',\'6\') || $user->isSuperadmin()', //data anggota
            ),
            array('allow',
                'actions' => array('loadbagian'),
                'expression' => '$user->getprivileges(\'view\',\'6\') || $user->getprivileges(\'view\',\'8\') || $user->isSuperadmin()', //data anggota
            ),
            array('allow',
                'actions' => array('create','kode'),
                'expression' => '$user->getprivileges(\'create\',\'6\') || $user->isSuperadmin()', //data anggota
            ),
            array('allow',
                'actions' => array('update'),
                'expression' => '$user->getprivileges(\'edit\',\'6\')|| $user->isSuperadmin()', //data anggota
            ),
            array('allow',
                'actions' => array('delete'),
                'expression' => '$user->getprivileges(\'del\',\'6\') || $user->isSuperadmin()', //data anggota
            ), 
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id) {
        $this->render('view', array(
            'model' => $this->loadModel($id),
        ));
    }

    public function actionCreate($bagianid="") {
        $model = new Subbagian;
		
        $this->performAjaxValidation($model);
        if (isset($_POST['Subbagian'])) {
            $model->attributes = $_POST['Subbagian'];
			$subbagianid = Globals::newID("tmsubbagian", "subbagianid");
            $model->subbagianid = $subbagianid;
			$model->tahun = Yii::app()->user->getTahun();
			$model->attributes = array_merge($model->attributes,$this->getLogAddDataInfo());
			if ($model->save()) {
                //Globals::AdminLogging("create:bagian:" . $model->bagianid . "");
                //$this->redirect(array('view', 'bagianid' => $model->bagianid));
				$this->redirect(array('subbagian/admin', 'filterbagianid'=>$model->bagianid));
            }
        }else{
			if ($bagianid!="") {
	            $model->bagianid = $bagianid;
	        }
		}
		Yii::app()->clientScript->registerCoreScript('jquery.ui');
		$this->render('create', array(
            'model' => $model,
        ));
    }

    public function actionUpdate($subbagianid) {
        $model = $this->loadModel($subbagianid);
		
        $this->performAjaxValidation($model);

        if (isset($_POST['Subbagian'])) {
            $model->attributes = $_POST['Subbagian'];
			$model->attributes = array_merge($model->attributes,$this->getLogEditDataInfo());
            if ($model->save()) {
				//Globals::AdminLogging("update:bagian:" . $model->bagianid . "");
               	//$this->redirect(array('subbagian/	admin'));
				$this->redirect(array('subbagian/admin', 'filterbagianid'=>$model->bagianid));
            }
        }
		Yii::app()->clientScript->registerCoreScript('jquery.ui');
        $this->render('update', array(
            'model' => $model,
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($subbagianid) {
        $model = $this->loadModel($subbagianid);
		$bagianid = $model->bagianid;
        $this->performAjaxValidation($model);
		$model->attributes = $this->getLogDeleteDataInfo();
        if ($model->save()) {
			//Globals::AdminLogging("update:bagian:" . $model->bagianid . "");
           	$this->redirect(array('subbagian/admin', 'filterbagianid'=>""));
        }
        if (!isset($_GET['ajax']))
            $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
    }

    /**
     * Lists all models.
     */
    public function actionIndex() {
        $dataProvider = new CActiveDataProvider('Subbagian');
        $this->render('index', array(
            'dataProvider' => $dataProvider,
        ));
    }

   
    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer the ID of the model to be loaded
     */
    public function loadModel($id) {
        $model = Subbagian::model()->findByPk($id);
        if ($model === null)
            throw new CHttpException(404, 'The requested page does not exist.');
        return $model;
    }
	
	public function actionAdmin($bagianid="") {
        $model = new Subbagian('search');
        $model->unsetAttributes();  // clear any default values
        if (isset($_GET['Subbagian'])) {
            $model->attributes = $_GET['Subbagian'];
        }
		if (isset($_GET['filterbagianid'])) $model->bagianid = $_GET['filterbagianid'];
		else if ($bagianid!="") $model->bagianid = $bagianid;
		$criteria = new CDbCriteria();
        $criteria->select = 't.*, tr.kode as bagiankode, tr.nama as bagiannama';
		$criteria->addCondition("t.dlt = '0'");
		//$criteria->addCondition("t.tahun = '".Yii::app()->user->getTahun()."'");
		if (isset($_GET['searchtext']) && $_GET['searchtext'] != '') {
            $criteria->addCondition('t.kode LIKE :searchtext or t.nama LIKE :searchtext ');
            $criteria->params = array(':searchtext' => '%' . $_GET['searchtext'] . '%');
        }
		if ($model->bagianid != '' && $model->bagianid != '-') {
            $criteria->addCondition("t.bagianid = '".$model->bagianid."' ");
        }
        $criteria->join .= " LEFT JOIN tmbagian tr ON tr.bagianid=t.bagianid and tr.dlt='0' ";
        $dataProvider = new CActiveDataProvider('Subbagian', array('criteria' => $criteria,
            'pagination' => array('pageSize' => 20),
            'sort' => array(
                'defaultOrder' => 'tr.kode, t.kode, t.nama',
            ),));

        $this->render('admin', array(
            'dataProvider' => $dataProvider,
            'model' => $model
        ));
    }
    /**
     * Performs the AJAX validation.
     * @param CModel the model to be validated
     */
    protected function performAjaxValidation($model) {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'subbagian-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }

    public function actionLoadBagian() {
        $sql = "";
		$filter = "";
		/*$modeluser = Users::model()->findByPk(Yii::app()->user->id);
		if ($modeluser->grup=="2"){
			if (!is_null($modeluser->bagianid) && $modeluser->bagianid != '' && $modeluser->bagianid != '-') {
	            $filter .= " and bagianid = '".$modeluser->bagianid."' ";
	        }
		}*/
		if (isset($_POST['isall']) && $_POST['isall']!="")
			$sql = " SELECT '-' as bagianid,'--FILTER BAGIAN--' as bagianvw, 1 as urutan UNION ALL ";
		$sql .= "SELECT a.bagianid,concat(a.kode,' ',a.nama) as bagianvw, 2 as urutan 
				FROM tmbagian a 
				where a.dlt='0' 
				and a.tahun = '".Yii::app()->user->getTahun()."'
				order by urutan, bagianvw";
        $rows = Yii::app()->db->createCommand($sql)->queryAll();

        foreach ($rows as $row) {
            echo CHtml::tag('option', array('value' => $row['bagianid']), CHtml::encode($row['bagianvw']), true);
        }
    }
	
	public function actionKode() {
        try {
            $sql = "select coalesce(max(cast(replace(kode,'.','') as integer))+1,1) as kode from tmsubbagian where dlt='0' and bagianid='$_POST[bagianid]'";
            $nextKode = "01.";
            $results = Yii::app()->db->createCommand($sql)->queryAll();
            foreach ($results AS $result) {
                $nextKode = $result['kode'];
            }

            while (strlen($nextKode) < 2) {
                $nextKode = "0" . $nextKode;
            }

            echo $nextKode . ".";
        } catch (Exception $e) {
            echo "01.";
        }
    }

   

}

protected/views/subbagian/_form.php
<?php
/* @var $this SubbagianController */
/* @var $model Subbagian */
/* @var $form CActiveForm */
Yii::import('ext.select2.Select2');
?>
<header class="panel_header">
	<div class="actions panel_actions pull-right"></div>

</header>

<div class="content-body">
    <div class="row">
		<div class="col-12">
           <div class="card"><div class="card-body">
        <?php
        $form = $this->beginWidget('CActiveForm', array(
            'id' => 'subbagian-form',
            'method' => 'POST',
            'enableAjaxValidation' => false,
            'clientOptions' => array(
                'validateOnSubmit' => true,
                'validateOnChange' => true
            ),
            'htmlOptions' => array(
                'enctype' => 'multipart/form-data',
            )
        ));
        ?>
        <?php echo $form->errorSummary($model); ?>
        <div class="form-group">
            <div class="col-lg-12">
                <?php echo $form->labelEx($model, 'bagian'); ?><br>
                <?php
                    echo Select2::activeDropDownList($model, 'bagianid', array('' => ''), array(
                        'prompt' => 'PILIH SUB BAGIAN',
                        'class' => 'col-lg-6', 'style' => 'padding:0px',
						'onchange' => 'getKode()',
						'selected' => 'selected'
                    ));
                ?>
                <?php echo $form->error($model, 'bagianid'); ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-12">
                <?php echo $form->labelEx($model, 'kode'); ?>
                <?php echo $form->textField($model, 'kode', array('size' => 60, 'maxlength' => 90, 'class' => 'form-control', 'placeholder' => 'Kode')); ?>
                <?php echo $form->error($model, 'kode'); ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-12">
                <?php echo $form->labelEx($model, 'nama'); ?>
                <?php echo $form->textField($model, 'nama', array('size' => 60, 'maxlength' => 90, 'class' => 'form-control', 'placeholder' => 'Nama Unit Kerja')); ?>
                <?php echo $form->error($model, 'nama'); ?>
            </div>
        </div>
		<div class="form-group">
            <div class="col-lg-12">
                <?php echo $form->labelEx($model, 'alamat'); ?>
                <?php echo $form->textArea($model, 'alamat', array('size' => 60, 'maxlength' => 90, 'class' => 'form-control', 'placeholder' => 'Alamat')); ?>
                <?php echo $form->error($model, 'alamat'); ?>
            </div>
        </div>
		<div class="form-group">
            <div class="col-lg-12">
                <?php echo $form->labelEx($model, 'keterangan'); ?>
                <?php echo $form->textArea($model, 'keterangan', array('size' => 60, 'maxlength' => 90, 'class' => 'form-control', 'placeholder' => 'Keterangan')); ?>
                <?php echo $form->error($model, 'keterangan'); ?>
            </div>
        </div>
		<div class="col-lg-12">
            <br/><br/>
            <?php echo CHtml::submitButton($model->isNewRecord ? 'Tambah' : 'Update', array('class' => 'btn btn-primary')); ?>
            <button type="button" class="btn btn-inverse" onclick="window.location.href='<?php echo CController::createUrl('subbagian/admin'); ?>';">Cancel</button>
        </div>
        <?php $this->endWidget(); ?>
    </div><!-- form -->
</div></div></div></div>

<?php
$ismode = "add";
if (!$model->isNewRecord) {
    $ismode = "edit";
}
?>

<script type="text/javascript">
    
	$(document).ready(function () {
        loadBagian();
    });
	
	function loadBagian() {
        $.ajax({
            url: "<?php echo CController::createUrl('subbagian/loadbagian') ?>",
            type: 'POST',
            data: {},
            success: function (data) {
                $('#<?php echo CHtml::activeId($model, 'bagianid') ?>').html(data);
                $('#' + '<?php echo CHtml::activeId($model, 'bagianid') ?>').select2().select2('val', '');
                $('#' + '<?php echo CHtml::activeId($model, 'bagianid') ?>').select2().select2('val', '<?php echo $model->bagianid; ?>');
				<?php if ($ismode == "add") { ?>
				    getKode();
				<?php } ?>
            },
            error: function (jqXHR, status, err) {
                //alert(err);
            }
        });
    }
    
    function getKode() {
        $.ajax({
            url: "<?php echo CController::createUrl('subbagian/kode') ?>",
            type: 'POST',
            data: {bagianid: $('#' + '<?php echo CHtml::activeId($model, 'bagianid') ?>').select2().select2('val')},
            success: function (data) {
                $('#<?php echo CHtml::activeId($model, 'kode') ?>').val(data);
            },
            error: function (jqXHR, status, err) {
                //alert(err);
            }
        });
    }

</script>

protected/views/subbagian/admin.php
<?php
/* @var $this SubbagianController */
/* @var $model Subbagian */

Yii::import('ext.select2.Select2');
?>

<div class="row page-titles">
    <div class="col-md-5 align-self-center">
        <h4 class="text-themecolor">Data Sub Bagian</h4>
    </div>
    <div class="col-md-7 align-self-center text-right">
        <div class="d-flex justify-content-end align-items-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="<?php echo $this->createUrl('site/index'); ?>">Home</a></li>
                <li class="breadcrumb-item active">Data Sub Bagian</li>
            </ol>
			<?php if (Yii::app()->user->getprivileges("create", "6") || Yii::app()->user->isSuperadmin()) { ?>
			<button type="button" onclick='js:document.location.href="<?php echo $this->createUrl('subbagian/create'); ?>"' class="btn btn-info d-none d-lg-block m-l-15"><i class="fa fa-plus-circle"></i> Tambah Sub Bagian</button>
			<?php } ?>
        </div>
    </div>
</div>

<div class="clearfix"></div>
<div class="search-form">
    
</div><!-- search-form -->
<div class="row">	
<div class="table-responsive" style="">
	<div class="card"><div class="card-body">
	<div class="form-group" id="" style="padding-right:15px;">
		<div class="row">
			<div class="col-lg-12">
			    <?php 
					echo Select2::activeDropDownList($model, 'bagianid', array('' => ''), array(
                        'prompt' => 'PILIH BAGIAN',
                        'class' => 'col-lg-12', 'selected' => 'selected', 'style' => 'padding:0px;'
                    ));
				?>
			</div>
		</div>
    	<br>
        <div class="row">
			<div class="col-lg-12"> 
                <?php echo CHtml::textField('searchtext','',array('size' => 60, 'maxlength' => 90, 'class' => 'form-control', 'placeholder' => 'Pencarian')); ?>
            </div>
        </div>
    </div>
    <?php
    $this->widget('zii.widgets.grid.CGridView', array(
        'id' => 'subbagian-grid',
        'itemsCssClass' => 'table table-hover',
        // 'filter' => $model,
        'dataProvider' => $dataProvider,
        'ajaxUrl' => $this->createUrl('subbagian/admin'),
        'pager' => array(
//            'prevPageLabel' => CHtml::tag('i', array('class' => 'fa fa-angle-double-left')),
//            'nextPageLabel' => CHtml::tag('i', array('class' => 'fa fa-angle-double-right')),
            'header' => 'Unit Kerja',
            'cssFile' => false,
            'htmlOptions' => array(
                'class' => 'pagination pagination-lg',
            ),
        ),
//        'dataProvider' => $model->search(),
        'columns' => array(
            // 'id',
            array(
                'header' => '',
                'name' => 'bagianship_id',
                'type' => 'raw',
                'htmlOptions' => array('style' => 'font-size:15px;'),
                'value' => function($data) {
		            return "<font size='3px'>Bagian : ".$data['bagiannama']."</font><br/>".
					$data['bagiankode'] . $data['kode'] . " " . $data['nama'];
		        },
            ),
            array(
                'template' => '{update}{delete}',
                'class' => 'CButtonColumn',
                'htmlOptions' => array('width' => 90, 'style' => 'text-align: center;'),
                'buttons' => array(
                    'update' => array(
                        'url' => 'Yii::app()->createUrl("/subbagian/update", array("subbagianid"=>$data["subbagianid"]))',
                        'visible' => '(!Yii::app()->user->getprivileges("edit", "6") && !Yii::app()->user->isSuperadmin())?0:1',
                    ),
                    'delete' => array(
                        'url' => 'Yii::app()->createUrl("/subbagian/delete", array("subbagianid"=>$data["subbagianid"]))',
                        'visible' => '(!Yii::app()->user->getprivileges ("del", "6") && !Yii::app()->user->isSuperadmin())?0:1',
                    ),
                ),
            ),
        ),
    ));
    ?>
</div></div></div></div>
<script>
    function loadBagian() {
        $.ajax({
            url: "<?php echo CController::createUrl('subbagian/loadbagian') ?>",
            type: 'POST',
            data: {isall:'true'},
            success: function (data) {
                $('#<?php echo CHtml::activeId($model, 'bagianid') ?>').val('');
                $('#<?php echo CHtml::activeId($model, 'bagianid') ?>').html(data);
				if ("<?php echo $model->bagianid; ?>"!="")
                	$('#<?php echo CHtml::activeId($model, 'bagianid') ?>').select2().select2('val', "<?php echo $model->bagianid; ?>");
            },
            error: function (jqXHR, status, err) {
                //alert(err);
            }
        });
    }
	function tambahData() {
        js:document.location.href="<?php echo CController::createUrl('subbagian/create') ?>/bagianid/"+$('#<?php echo CHtml::activeId($model, 'bagianid') ?>').val();
    }
	$(document).ready(function () {
        loadBagian();
		$('#searchtext').keyup(function(e){
			if(e.keyCode == 13)
		    {
				$.fn.yiiGridView.update('subbagian-grid', {
					//data: $(this).serialize()
					data: {searchtext:$('#searchtext').val(),filterbagianid: $('#<?php echo CHtml::activeId($model, 'bagianid') ?>').val()},
				});
				return false;
			}
		});
		$('#<?php echo CHtml::activeId($model, 'bagianid') ?>').change(function(e){
			$.fn.yiiGridView.update('subbagian-grid', {
				//data: $(this).serialize()
				data: {searchtext:$('#searchtext').val(),filterbagianid: $('#<?php echo CHtml::activeId($model, 'bagianid') ?>').val()},
			});
			return false;
		});
    });
</script>

protected/views/subbagian/create.php
<?php
/* @var $this SubbagianController */
/* @var $model Subbagian */

?>
<div class="row page-titles">
    <div class="col-md-5 align-self-center">
        <h4 class="text-themecolor">Tambah Sub Bagian</h4>
    </div>
    <div class="col-md-7 align-self-center text-right">
        <div class="d-flex justify-content-end align-items-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="<?php echo $this->createUrl('subbagian/admin'); ?>">Data Sub Bagian</a></li>
                <li class="breadcrumb-item active">Tambah Sub Bagian</li>
            </ol>
        </div>
    </div>
</div>
<div class="clearfix"></div>

<?php echo $this->renderPartial('_form', array('model' => $model)); ?>

protected/views/subbagian/index.php
<?php
/* @var $this MemberController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Members',
);

$this->menu=array(
	array('label'=>'Create Unit Kerja', 'url'=>array('create')),
	array('label'=>'Manage Unit Kerja', 'url'=>array('admin')),
);
?>

<h1>Members</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/views/subbagian/update.php
<?php
/* @var $this SubbagianController */
/* @var $model Subbagian */

$this->breadcrumbs = array(
    'Sub Bagian' => array('admin'),
    'Ubah Sub Bagian',
);
?>


<div class="row page-titles">
    <div class="col-md-5 align-self-center">
        <h4 class="text-themecolor">Ubah Sub Bagian</h4>
    </div>
    <div class="col-md-7 align-self-center text-right">
        <div class="d-flex justify-content-end align-items-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="<?php echo $this->createUrl('subbagian/admin'); ?>">Data Sub Bagian</a></li>
                <li class="breadcrumb-item active">Ubah Sub Bagian</li>
            </ol>
        </div>
    </div>
</div>
<div class="clearfix"></div>

<?php echo $this->renderPartial('_form', array('model' => $model)); ?>