protected/models/Pengumuman.php
<?php

/**
 * This is the model class for table "tspengumuman".
 *
 * The followings are the available columns in table 'tspengumuman':
 * @property string $pengumumanid
 * @property string $pengirim
 * @property string $judul
 * @property string $keterangan
 * @property string $tglpengumuman
 * @property integer $flag
 * @property integer $status
 * @property string $img
 * @property string $opadd
 * @property string $tgladd
 * @property string $pcadd
 * @property string $opedit
 * @property string $tgledit
 * @property string $pcedit
 * @property boolean $dlt
 */
class Pengumuman extends CActiveRecord
{
	/**
	 * Returns the static model of the specified AR class.
	 * @return Pengumuman the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'tspengumuman';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('pengumumanid', 'required'),
			array('flag, status', 'numerical', 'integerOnly'=>true),
			array('pengumumanid', 'length', 'max'=>20),
			array('pengirim, judul', 'length', 'max'=>150),
			array('img', 'length', 'max'=>30),
			array('opadd, pcadd, opedit, pcedit', 'length', 'max'=>40),
			array('keterangan, tglpengumuman, tgladd, tgledit, dlt', 'safe'),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('pengumumanid, pengirim, judul, keterangan, tglpengumuman, flag, status, img, opadd, tgladd, pcadd, opedit, tgledit, pcedit, dlt', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'pengumumanid' => 'Pengumumanid',
			'pengirim' => 'Pengirim',
			'judul' => 'Judul',
			'keterangan' => 'Keterangan',
			'tglpengumuman' => 'Tglpengumuman',
			'flag' => 'Flag',
			'status' => 'Status',
			'img' => 'Img',
			'opadd' => 'Opadd',
			'tgladd' => 'Tgladd',
			'pcadd' => 'Pcadd',
			'opedit' => 'Opedit',
			'tgledit' => 'Tgledit',
			'pcedit' => 'Pcedit',
			'dlt' => 'Dlt',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('pengumumanid',$this->pengumumanid,true);
		$criteria->compare('pengirim',$this->pengirim,true);
		$criteria->compare('judul',$this->judul,true);
		$criteria->compare('keterangan',$this->keterangan,true);
		$criteria->compare('tglpengumuman',$this->tglpengumuman,true);
		$criteria->compare('flag',$this->flag);
		$criteria->compare('status',$this->status);
		$criteria->compare('img',$this->img,true);
		$criteria->compare('opadd',$this->opadd,true);
		$criteria->compare('tgladd',$this->tgladd,true);
		$criteria->compare('pcadd',$this->pcadd,true);
		$criteria->compare('opedit',$this->opedit,true);
		$criteria->compare('tgledit',$this->tgledit,true);
		$criteria->compare('pcedit',$this->pcedit,true);
		$criteria->compare('dlt',$this->dlt);

		return new CActiveDataProvider(get_class($this), array(
			'criteria'=>$criteria,
		));
	}
}

protected/controllers/PengumumanController.php
<?php

class PengumumanController extends Controller {

    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/column2';

    /**
     * @return array action filters
     */
    public function filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
            'postOnly + delete', // we only allow deletion via POST request
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules() {
        return array(
            array('allow',
                'actions' => array('admin', 'view'),
                'expression' => '$user->getprivileges(\'view\',\'304\') || $user->isSuperadmin()', //data anggota
            ),
            array('allow',
                'actions' => array('create','kode'),
                'expression' => '$user->getprivileges(\'create\',\'304\') || $user->isSuperadmin()', //data anggota
            ),
            array('allow',
                'actions' => array('update'),
                'expression' => '$user->getprivileges(\'edit\',\'304\')|| $user->isSuperadmin()', //data anggota
            ),
            array('allow',
                'actions' => array('delete'),
                'expression' => '$user->getprivileges(\'del\',\'304\') || $user->isSuperadmin()', //data anggota
            ), 
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id) {
        $this->render('view', array(
            'model' => $this->loadModel($id),
        ));
    }

    public function actionCreate($pengumumanid="") {
        $model = new Pengumuman;
		
        $this->performAjaxValidation($model);
        if (isset($_POST['Pengumuman'])) {
            $model->attributes = $_POST['Pengumuman'];
			$pengumumanid = Globals::newID("tspengumuman", "pengumumanid");
            $model->pengumumanid = $pengumumanid;
            $model->tglpengumuman = $this->datePostgres($model->tglpengumuman);
            $model->flag = '1';
			$model->attributes = array_merge($model->attributes,$this->getLogAddDataInfo());
			if ($model->save()) {
                //Globals::AdminLogging("create:pengumuman:" . $model->pengumumanid . "");
				$this->redirect(array('pengumuman/admin'));
            }
        }else{
            $model->tglpengumuman = $this->dateIndo($model->tglpengumuman);
		}
		Yii::app()->clientScript->registerCoreScript('jquery.ui');
		$this->render('create', array(
            'model' => $model,
        ));
    }

    public function actionUpdate($pengumumanid) {
        $model = $this->loadModel($pengumumanid);
		
        $this->performAjaxValidation($model);

        if (isset($_POST['Pengumuman'])) {
            $model->attributes = $_POST['Pengumuman'];
            $model->flag = '1';
			$model->attributes = array_merge($model->attributes,$this->getLogEditDataInfo());
            $model->tglpengumuman = $this->datePostgres($model->tglpengumuman);
            if ($model->save()) {
				//Globals::AdminLogging("update:pengumuman:" . $model->pengumumanid . "");
				$this->redirect(array('pengumuman/admin'));
            }
        }
		else {
            $model->tglpengumuman = $this->dateIndo($model->tglpengumuman);
		}
		Yii::app()->clientScript->registerCoreScript('jquery.ui');
        $this->render('update', array(
            'model' => $model,
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($pengumumanid) {
        $model = $this->loadModel($pengumumanid);
		$this->performAjaxValidation($model);
		$model->attributes = $this->getLogDeleteDataInfo();
        if ($model->save()) {
			//Globals::AdminLogging("update:pengumuman:" . $model->pengumumanid . "");
           	$this->redirect(array('pengumuman/admin'));
        }
        if (!isset($_GET['ajax']))
            $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
    }

    /**
     * Lists all models.
     */
    public function actionIndex() {
        $dataProvider = new CActiveDataProvider('Pengumuman');
        $this->render('index', array(
            'dataProvider' => $dataProvider,
        ));
    }

   
    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer the ID of the model to be loaded
     */
    public function loadModel($id) {
        $model = Pengumuman::model()->findByPk($id);
        if ($model === null)
            throw new CHttpException(404, 'The requested page does not exist.');
        return $model;
    }
	
	public function actionAdmin($pengumumanid="") {
        $model = new Pengumuman('search');
        $model->unsetAttributes();  // clear any default values
        if (isset($_GET['Pengumuman'])) {
            $model->attributes = $_GET['Pengumuman'];
        }
		$criteria = new CDbCriteria();
        $criteria->select = 't.*';
		$criteria->addCondition("t.dlt = '0'");
		//$criteria->addCondition("t.tahun = '".Yii::app()->user->getTahun()."'");
		if (isset($_GET['searchtext']) && $_GET['searchtext'] != '') {
            $criteria->addCondition('t.judul LIKE :searchtext or t.keterangan LIKE :searchtext ');
            $criteria->params = array(':searchtext' => '%' . $_GET['searchtext'] . '%');
        }
        $dataProvider = new CActiveDataProvider('Pengumuman', array('criteria' => $criteria,
            'pagination' => array('pageSize' => 20),
            'sort' => array(
                'defaultOrder' => 't.tglpengumuman, t.pengirim',
            ),));

        $this->render('admin', array(
            'dataProvider' => $dataProvider,
            'model' => $model
        ));
    }
    /**
     * Performs the AJAX validation.
     * @param CModel the model to be validated
     */
    protected function performAjaxValidation($model) {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'pengumuman-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }
}

protected/views/pengumuman/_form.php
<?php
/* @var $this PengumumanController */
/* @var $model Pengumuman */
/* @var $form CActiveForm */
Yii::import('ext.select2.Select2');
?>
<header class="panel_header">
	<div class="actions panel_actions pull-right"></div>

</header>

<div class="content-body">
    <div class="row">
		<div class="col-12">
           <div class="card"><div class="card-body">
        <?php
        $form = $this->beginWidget('CActiveForm', array(
            'id' => 'pengumuman-form',
            'method' => 'POST',
            'enableAjaxValidation' => false,
            'clientOptions' => array(
                'validateOnSubmit' => true,
                'validateOnChange' => true
            ),
            'htmlOptions' => array(
                'enctype' => 'multipart/form-data',
            )
        ));
        ?>
        <?php echo $form->errorSummary($model); ?>
        <div class="form-group">
	        	<div class="col-lg-4">
				<?php echo $form->labelEx($model, 'tanggal pengumuman'); ?>
                <?php
                $this->widget('zii.widgets.jui.CJuiDatePicker', array(
                    'model' => $model,
                    'language' => 'id',
                    'attribute' => 'tglpengumuman',
                    'options' => array('showAnim'=>'fold','dateFormat'=>'dd-mm-yy', 'changeMonth'=>true, 'changeYear'=>true),
                    'htmlOptions' => array('readonly' => false, 'class' => 'form-control', 'maxlength' => 10)
                ));
                ?> 
				</div>
        </div>
        <div class="form-group">
            <div class="col-lg-12">
                <?php echo $form->labelEx($model, 'pengirim'); ?>
                <?php echo $form->textField($model, 'pengirim', array('size' => 60, 'maxlength' => 150, 'class' => 'form-control', 'placeholder' => 'Pengirim')); ?>
                <?php echo $form->error($model, 'pengirim'); ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-12">
                <?php echo $form->labelEx($model, 'judul'); ?>
                <?php echo $form->textField($model, 'judul', array('size' => 60, 'maxlength' => 1200, 'class' => 'form-control', 'placeholder' => 'Judul')); ?>
                <?php echo $form->error($model, 'judul'); ?>
            </div>
        </div>
		<div class="form-group">
            <div class="col-lg-12">
                <?php echo $form->labelEx($model, 'keterangan'); ?>
                <?php echo $form->textArea($model, 'keterangan', array('size' => 60, 'maxlength' => 250, 'class' => 'form-control', 'placeholder' => 'Keterangan')); ?>
                <?php echo $form->error($model, 'keterangan'); ?>
            </div>
        </div>
		<div class="form-group">
            <div class="col-lg-12">
                <?php echo $form->labelEx($model, 'status'); ?> &nbsp;
				<?php echo $form->checkBox($model,'status',array('value' => '1', 'uncheckValue'=>'0')); ?>
                <?php echo $form->error($model, 'status'); ?>
            </div>
        </div>
		<div class="col-lg-12">
            <br/><br/>
            <?php echo CHtml::submitButton($model->isNewRecord ? 'Tambah' : 'Update', array('class' => 'btn btn-primary')); ?>
            <button type="button" class="btn btn-inverse" onclick="window.location.href='<?php echo CController::createUrl('pengumuman/admin'); ?>';">Cancel</button>
        </div>
        <?php $this->endWidget(); ?>
    </div><!-- form -->
</div></div></div></div>

<?php
$ismode = "add";
if (!$model->isNewRecord) {
    $ismode = "edit";
}
?>

<script type="text/javascript">
    
	$(document).ready(function () {
		
    });

</script>

protected/views/pengumuman/admin.php
<?php
/* @var $this PengumumanController */
/* @var $model Pengumuman */

Yii::import('ext.select2.Select2');
?>

<div class="row page-titles">
    <div class="col-md-5 align-self-center">
        <h4 class="text-themecolor">Data Pengumuman</h4>
    </div>
    <div class="col-md-7 align-self-center text-right">
        <div class="d-flex justify-content-end align-items-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="<?php echo $this->createUrl('site/index'); ?>">Home</a></li>
                <li class="breadcrumb-item active">Data Pengumuman</li>
            </ol>
			<?php if (Yii::app()->user->getprivileges("create", "304") || Yii::app()->user->isSuperadmin()) { ?>
			<button type="button" onclick='js:document.location.href="<?php echo $this->createUrl('pengumuman/create'); ?>"' class="btn btn-info d-none d-lg-block m-l-15"><i class="fa fa-plus-circle"></i> Tambah Pengumuman</button>
			<?php } ?>
        </div>
    </div>
</div>

<div class="clearfix"></div>
<div class="search-form">
    
</div><!-- search-form -->
<div class="row">
        
		
    </div>
<div class="row">	
<div class="table-responsive">
	<div class="card"><div class="card-body">
	<div class="form-group" id="" style="padding-right:0px;">
			<div> 
                <?php echo CHtml::textField('searchtext','',array('size' => 60, 'maxlength' => 90, 'class' => 'form-control', 'placeholder' => 'Pencarian')); ?>
            </div>
        </div>
    <?php
    $this->widget('zii.widgets.grid.CGridView', array(
        'id' => 'pengumuman-grid',
        'itemsCssClass' => 'table table-hover color-table info-table',
        // 'filter' => $model,
        'dataProvider' => $dataProvider,
        'ajaxUrl' => $this->createUrl('pengumuman/admin'),
        'pager' => array(
//            'prevPageLabel' => CHtml::tag('i', array('class' => 'fa fa-angle-double-left')),
//            'nextPageLabel' => CHtml::tag('i', array('class' => 'fa fa-angle-double-right')),
            'header' => 'Pengumuman',
            'cssFile' => false,
            'htmlOptions' => array(
                'class' => 'pagination pagination-lg',
            ),
        ),
//        'dataProvider' => $model->search(),
        'columns' => array(
            // 'id',
            array(
                'header' => 'Tanggal',
                'name' => 'tglpengumumanship_id',
                'type' => 'raw',
                'htmlOptions' => array('style' => 'font-size:15px;'),
                'value' => function($data) {
		            return $data['tglpengumuman'];
		        },
            ),
            array(
                'header' => 'Pengirim',
                'name' => 'pengirimship_id',
                'type' => 'raw',
                'htmlOptions' => array('style' => 'font-size:15px;'),
                'value' => function($data) {
		            return $data['pengirim'];
		        },
            ),
            array(
                'header' => 'Judul',
                'name' => 'judulship_id',
                'type' => 'raw',
                'htmlOptions' => array('style' => 'font-size:15px;'),
                'value' => function($data) {
		            return $data['judul'];
		        },
            ),
            array(
                'header' => 'Status',
                'name' => 'statusship_id',
                'type' => 'raw',
                'htmlOptions' => array('style' => 'font-size:15px;'),
                'value' => function($data) {
		            return ($data['status'] == '1') ? 'Aktif' : 'Tidak Aktif';
		        },
            ),
            array(
                'template' => '{update}{delete}',
                'class' => 'CButtonColumn',
                'htmlOptions' => array('width' => 90, 'style' => 'text-align: center;'),
                'buttons' => array(
                    'update' => array(
                        'url' => 'Yii::app()->createUrl("/pengumuman/update", array("pengumumanid"=>$data["pengumumanid"]))',
                        'visible' => '(!Yii::app()->user->getprivileges("edit", "304") && !Yii::app()->user->isSuperadmin())?0:1',
                    ),
                    'delete' => array(
                        'url' => 'Yii::app()->createUrl("/pengumuman/delete", array("pengumumanid"=>$data["pengumumanid"]))',
                        'visible' => '(!Yii::app()->user->getprivileges ("del", "304") && !Yii::app()->user->isSuperadmin())?0:1',
                    ),
                ),
            ),
        ),
    ));
    ?>
</div></div></div></div>
<script>
    function tambahData() {
        js:document.location.href="<?php echo CController::createUrl('pengumuman/create') ?>";
    }
	$(document).ready(function () {
        $('#searchtext').keyup(function(e){
			if(e.keyCode == 13)
		    {
				$.fn.yiiGridView.update('pengumuman-grid', {
					data: {searchtext:$('#searchtext').val()},
				});
				return false;
			}
		});
    });
</script>

protected/views/pengumuman/create.php
<?php
/* @var $this PengumumanController */
/* @var $model Pengumuman */

?>
<div class="row page-titles">
    <div class="col-md-5 align-self-center">
        <h4 class="text-themecolor">Tambah Pengumuman</h4>
    </div>
    <div class="col-md-7 align-self-center text-right">
        <div class="d-flex justify-content-end align-items-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="<?php echo $this->createUrl('pengumuman/admin'); ?>">Data Pengumuman</a></li>
                <li class="breadcrumb-item active">Tambah Pengumuman</li>
            </ol>
        </div>
    </div>
</div>
<div class="clearfix"></div>

<?php echo $this->renderPartial('_form', array('model' => $model)); ?>

protected/views/pengumuman/index.php
<?php
/* @var $this MemberController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Members',
);

$this->menu=array(
	array('label'=>'Create Unit Kerja', 'url'=>array('create')),
	array('label'=>'Manage Unit Kerja', 'url'=>array('admin')),
);
?>

<h1>Members</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/views/pengumuman/update.php
<?php
/* @var $this PengumumanController */
/* @var $model Pengumuman */

$this->breadcrumbs = array(
    'Pengumuman' => array('admin'),
    'Ubah Pengumuman',
);
?>


<div class="row page-titles">
    <div class="col-md-5 align-self-center">
        <h4 class="text-themecolor">Ubah Pengumuman</h4>
    </div>
    <div class="col-md-7 align-self-center text-right">
        <div class="d-flex justify-content-end align-items-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="<?php echo $this->createUrl('pengumuman/admin'); ?>">Data Pengumuman</a></li>
                <li class="breadcrumb-item active">Ubah Pengumuman</li>
            </ol>
        </div>
    </div>
</div>
<div class="clearfix"></div>

<?php echo $this->renderPartial('_form', array('model' => $model)); ?>