protected/models/Users.php
<?php

/**
 * This is the model class for table "users".
 *
 * The followings are the available columns in table 'users':
 * @property string $userid
 * @property string $username
 * @property string $password
 * @property string $status
 * @property integer $roleid
 *
 * The followings are the available model relations:
 * @property Role $role
 * @property VerificationLog[] $verificationLogs
 */
class Users extends CActiveRecord {

    public $repeat_password;
    //will hold the encrypted password for update actions.
    public $initialPassword;
	public $subunitnama;
	public $subbagnama;

    /**
     * Returns the static model of the specified AR class.
     * @param string $className active record class name.
     * @return Users the static model class
     */
    public static function model($className = __CLASS__) {
        return parent::model($className);
    }

    /**
     * @return string the associated database table name
     */
    public function tableName() {
        return 'tbmuser';
    }

    /**
     * @return array validation rules for model attributes.
     */
    public function rules() {
        // NOTE: you should only define rules for those attributes that
        // will receive user inputs.
        return array(
            array('password, repeat_password', 'required', 'message' => "Passwords wajib diisi", 'on' => 'insert'),
            array('roleid', 'numerical', 'integerOnly' => true),
			array('userid, unitid, subunitid, subbagid, pcadd, opedit, pcedit', 'length', 'max'=>20),
            array('username', 'length', 'max' => 40),
            array('nama', 'length', 'max' => 50),
            array('password, repeat_password', 'length', 'min' => 6, 'max' => 40),
            array('status, dlt', 'length', 'max' => 1),
			array('tgladd, tgledit', 'safe'),
//            array('photo_type', 'length', 'max' => 20),
//            array('photo', 'safe'),
      //      array('password', 'compare', 'compareAttribute' => 'repeat_password', 'message' => "Passwords tidak sesuai"),
//            array('username', 'ValidatorNameGoesHere', 'readOnly' => true, 'on' => 'update'),
            // The following rule is used by search().
            // Please remove those attributes that should not be searched.
            array('userid, username, password, status, roleid, id_prov, id_kab, id_kec, photo, photo_type', 'safe', 'on' => 'search'),
        );
    }

    /**
     * @return array relational rules.
     */
    public function relations() {
        // NOTE: you may need to adjust the relation name and the related
        // class name for the relations automatically generated below.
        return array(
            'role' => array(self::BELONGS_TO, 'Role', 'roleid'),
            'verificationLogs' => array(self::HAS_MANY, 'VerificationLog', 'user_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
            'userid' => 'ID',
			'username' => 'Username',
            'password' => 'Password',
            'status' => 'Status',
            'roleid' => 'Tipe',
            'photo' => 'Foto'
        );
    }

    /**
     * Retrieves a list of models based on the current search/filter conditions.
     * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
     */
    public function search() {
        // Warning: Please modify the following code to remove attributes that
        // should not be searched.

        $criteria = new CDbCriteria;

        $criteria->compare('userid', $this->userid, true);
        $criteria->compare('username', $this->username, true);
        $criteria->compare('password', $this->password, true);
        $criteria->compare('status', $this->status, true);
        $criteria->compare('roleid', $this->roleid);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function validatePassword($username, $password) {
        //$password = str_replace("'","''",$password);
      
        $sql="select password=crypt('$password',password) as password from tbmuser where lower(username)=lower('$username') and dlt='0'";
        $rows = Yii::app()->db->createCommand($sql)->queryAll();
        $result = $rows[0];
        $hasil = $result['password'];
        
        return $hasil;
    }

    public function encryptPassword($password) {
        $sql="select crypt('$password',password) as password from tbmuser ";
        $rows = Yii::app()->db->createCommand($sql)->queryAll();
        $result = $rows[0];
        $hasil = $result['password'];
        
        return $hasil;
    }
    
    

    function getMenu() {
        $criteria = new CDbCriteria();
        $criteria->select = 'a.parent,a.menu,a.url';

        $criteria->condition = "a.ishide='0'";
        $dataProvider = new CActiveDataProvider('Menu', array('criteria' => $criteria,
            'pagination' => array('pageSize' => 100),
            'sort' => array(
                'defaultOrder' => 'id DESC',
        )));
        return $dataProvider;
    }

}

protected/controllers/UserController.php
<?php

class UserController extends Controller {

    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/column2';

    /**
     * @return array action filters
     */
    public function filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
            'postOnly + delete', // we only allow deletion via POST request
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules() {
        return array(
            array('allow',
                'actions' => array('akun', 'profil'),
                'users' => array('@'),
            ),
            array('allow',
                'actions' => array('admin', 'view','loadakses','loadpegawai'),
                'expression' => '$user->getprivileges(\'view\',\'302\') || $user->isSuperadmin()', //data anggota
            ),
            array('allow',
                'actions' => array('loadakses','password'),
                'expression' => '$user->getprivileges(\'view\',\'303\') || $user->isSuperadmin()', //data anggota
            ),
            array('allow',
                'actions' => array('create'),
                'expression' => '$user->getprivileges(\'create\',\'302\') || $user->isSuperadmin()', //data anggota
            ),
            array('allow',
                'actions' => array('update'),
                'expression' => '$user->getprivileges(\'edit\',\'302\')|| $user->isSuperadmin()', //data anggota
            ),
            array('allow',
                'actions' => array('delete'),
                'expression' => '$user->getprivileges(\'del\',\'302\') || $user->isSuperadmin()', //data anggota
            ), 
            array('allow',
                'actions' => array('adminverify','loadstatus'),
                'expression' => '$user->getprivileges(\'view\',\'304\') || $user->isSuperadmin()', //data verifikasi
            ),
            array('allow',
                'actions' => array('verify'),
                'expression' => '$user->getprivileges(\'edit\',\'304\')|| $user->isSuperadmin()', //data verifikasi
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id) {
        $this->render('view', array(
            'model' => $this->loadModel($id),
        ));
    }

    public function actionCreate($aksesid="") {
        $model = new User;
		
        $this->performAjaxValidation($model);
		$model->scenario='create';
        if (isset($_POST['User'])) {
            $model->attributes = $_POST['User'];
			$model->picture=CUploadedFile::getInstance($model,'picture');
			
			$folder_name = 'foto/';
			$userid = Globals::newID("tmuser", "userid");
			
			$valid = true;
			if ($model->pegawaiid == '') {
				$valid = false;
				$model->addError('pegawaiid', 'Pegawai harus dipilih terlebih dahulu');
			}
			else {
				$sql = "SELECT userid from tmuser where dlt = '0' and pegawaiid = '".$model->pegawaiid."' ";
		        $rows = Yii::app()->db->createCommand($sql)->queryAll();
				if (count($rows) > 0) {
					$valid = false;
					$model->addError('pegawaiid', 'Pegawai yang dipilih sudah memiliki username');
				}
			}
			
			//echo $model->pegawaiid.'-'.$valid;
			//var_dump($_POST);
			//var_dump($_FILES);
			//return;
			if ($valid) {
	            $model->userid = $userid;
				$model->status = '1';
				$model->tahun = Yii::app()->user->getTahun();
				$model->attributes = array_merge($model->attributes,$this->getLogAddDataInfo());
				if($model->validate())
				{
					//$userModel = User::model()->findByPk(Yii::app()->user->id);
					$pass = $model->encryptPassword($model->password);
					$model->password = $pass;
					
					if ($model->save()) {
						if ($model->picture != null && $model->picture != "") {
							$newfiles = $model->picture->name;
							$model->picture->saveAs($folder_name . $newfiles);
						}
		                //Globals::AdminLogging("create:unit:" . $model->aksesid . "");
		                //$this->redirect(array('view', 'aksesid' => $model->aksesid));
						$this->redirect(array('user/admin', 'filteraksesid'=>$model->aksesid));
		            }
	            }
			}
        }else{
			if ($aksesid!="") {
	            $model->aksesid = $aksesid;
	        }
		}
		Yii::app()->clientScript->registerCoreScript('jquery.ui');
		$this->render('create', array(
            'model' => $model,
        ));
    }

    public function actionUpdate($userid) {
        $model = $this->loadModel($userid);
		
        $this->performAjaxValidation($model);
		$model->scenario='update';
		
        if (isset($_POST['User'])) {
            $model->attributes = $_POST['User'];
			$model->picture=CUploadedFile::getInstance($model,'picture');
			$model->attributes = array_merge($model->attributes,$this->getLogEditDataInfo());
			
			$valid = true;
			if ($model->pegawaiid == '') {
				$valid = false;
				$model->addError('pegawaiid', 'Pegawai harus dipilih terlebih dahulu');
			}
			else {
				$sql = "SELECT userid from tmuser where dlt = '0' and pegawaiid = '".$model->pegawaiid."' and userid <> '".$userid."' ";
		        $rows = Yii::app()->db->createCommand($sql)->queryAll();
				if (count($rows) > 0) {
					$valid = false;
					$model->addError('pegawaiid', 'Pegawai yang dipilih sudah memiliki username');
				}
			}
			if ($model->password == '') {
				$valid = false;
				$model->addError('password', 'Isi password terlebih dahulu');
			}
			if ($valid) {
				$folder_name = 'foto/';
				if($model->validate())
				{
					//$userModel = User::model()->findByPk(Yii::app()->user->id);
					$pass = $model->encryptPassword($model->password);
					$model->password = $pass;
		            $model->tahun = Yii::app()->user->getTahun();
					if ($model->save()) {
						if (!empty($model->picture) && $model->picture != null && $model->picture != '') {
							$newfiles = $model->picture->name;
							$model->picture->saveAs($folder_name . $newfiles);
						}
						//Globals::AdminLogging("update:unit:" . $model->aksesid . "");
		               	//$this->redirect(array('user/	admin'));
						$this->redirect(array('user/admin', 'filteraksesid'=>$model->aksesid));
		            }
		        }
			}
        }
		Yii::app()->clientScript->registerCoreScript('jquery.ui');
        $this->render('update', array(
            'model' => $model,
        ));
    }

    public function actionAkun() {
        $model = $this->loadModel(Yii::app()->user->getuser('id'));
		
        $this->performAjaxValidation($model);
		$model->scenario='account';
		
        if (isset($_POST['User'])) {
            $model->attributes = $_POST['User'];
			$model->attributes = array_merge($model->attributes,$this->getLogEditDataInfo());
			
			if($model->validate())
			{
				//$userModel = User::model()->findByPk(Yii::app()->user->id);
				$pass = $model->encryptPassword($model->password);
				$model->password = $pass;
	            $model->tahun = Yii::app()->user->getTahun();
				if ($model->save()) {
					//Globals::AdminLogging("update:unit:" . $model->aksesid . "");
	               	//$this->redirect(array('user/	admin'));
					$this->redirect(array('user/akun'));
	            }
	        }
        }
		Yii::app()->clientScript->registerCoreScript('jquery.ui');
        $this->render('akun', array(
            'model' => $model,
        ));
    }

    public function actionProfil() {
        $this->breadcrumbs = array(
		    'Home' => array('admin','site'),
		    'Pengaturan Akun',
		);

        $model = $this->loadModel(Yii::app()->user->getuser('id'));
		
        $this->performAjaxValidation($model);
		$model->scenario='account';
		
        if (isset($_POST['User'])) {
            $model->attributes = $_POST['User'];
			$model->attributes = array_merge($model->attributes,$this->getLogEditDataInfo());
			
			if($model->validate())
			{
				//$userModel = User::model()->findByPk(Yii::app()->user->id);
				$pass = $model->encryptPassword($model->password);
				$model->password = $pass;
	            $model->tahun = Yii::app()->user->getTahun();
				if ($model->save()) {
					//Globals::AdminLogging("update:unit:" . $model->aksesid . "");
	               	//$this->redirect(array('user/	admin'));
					$this->redirect(array('user/admin', 'filteraksesid'=>$model->aksesid));
	            }
	        }
        }
		Yii::app()->clientScript->registerCoreScript('jquery.ui');
        $this->render('profil', array(
            'model' => $model,
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($userid) {
        $model = $this->loadModel($userid);
		$aksesid = $model->aksesid;
        $this->performAjaxValidation($model);
		$model->attributes = $this->getLogDeleteDataInfo();
        if ($model->save()) {
			//Globals::AdminLogging("update:unit:" . $model->aksesid . "");
           	$this->redirect(array('user/admin', 'filteraksesid'=>""));
        }
        if (!isset($_GET['ajax']))
            $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
    }

    /**
     * Lists all models.
     */
    public function actionIndex() {

protected/views/user/_form.php
<?php
/* @var $this UserController */
/* @var $model User */
/* @var $form CActiveForm */
Yii::import('ext.select2.Select2');
$baseUrl = Yii::app()->theme->baseUrl;
?>

<header class="panel_header">
	<div class="actions panel_actions pull-right"></div>

</header>
<div class="content-body">
    <div class="row">
		<div class="col-12">
           <div class="card"><div class="card-body">
        <?php
        $form = $this->beginWidget('CActiveForm', array(
            'id' => 'user-form',
            'method' => 'POST',
            'enableAjaxValidation' => false,
            'clientOptions' => array(
                'validateOnSubmit' => true,
                'validateOnChange' => true
            ),
            'htmlOptions' => array(
                'enctype' => 'multipart/form-data',
                'onsubmit'=>'return validate()',
				'class'=>'form-horizontal material',
            )
        ));
        ?>
        <?php echo $form->errorSummary($model); ?>
		<div class="form-group row">
			<?php echo $form->labelEx($model, 'hak akses', array('class' => 'control-label col-sm-2')); ?>
			<div class="col-sm-10">
			<?php
				echo Select2::activeDropDownList($model, 'aksesid', array('' => ''), array(
					'prompt' => 'PILIH HAK AKSES',
					'class' => 'col-sm-8', 'style' => 'padding:0px;font-family: Arial, Helvetica, sans-serif;',
					'onchange' => 'loadPegawai(false);',
					'selected' => 'selected'
				));
			?>
			<?php echo $form->error($model, 'aksesid'); ?>
			</div>
		</div>
		<div class="form-group row">
			<?php echo $form->labelEx($model, 'pegawai', array('class' => 'control-label col-sm-2')); ?>
			<div class="col-sm-10">
			<?php
				echo Select2::activeDropDownList($model, 'pegawaiid', array('' => ''), array(
					'prompt' => 'PILIH PEGAWAI',
					'class' => 'col-sm-8', 'style' => 'padding:0px;font-family: Arial, Helvetica, sans-serif;',
					'selected' => 'selected'
				));
			?>
			<?php echo $form->error($model, 'pegawaiid'); ?>
			</div>
		</div>
        <div class="form-group row">
            <?php echo $form->labelEx($model, 'nama lengkap', array('class' => 'control-label col-sm-2')); ?>
            <div class="col-lg-10">
                <?php echo $form->textField($model, 'nama', array('maxlength' => 90, 'class' => 'form-control', 'placeholder' => 'Nama Lengkap')); ?>
                <?php echo $form->error($model, 'nama'); ?>
            </div>
        </div>
        <div class="form-group row">
            <?php echo $form->labelEx($model, 'username', array('class' => 'control-label col-sm-2')); ?>
            <div class="col-lg-10">
                <?php echo $form->textField($model, 'username', array('maxlength' => 90, 'class' => 'form-control', 'placeholder' => 'Username')); ?>
                <?php echo $form->error($model, 'username'); ?>
            </div>
        </div>
        <div class="form-group row">
            <?php echo $form->labelEx($model, 'Password baru', array('class' => 'control-label col-sm-2')); ?>
            <div class="col-lg-4">
				<?php echo $form->passwordField($model, 'password', array('class'=>'form-control','placeholder'=>'Password Baru')); ?>
                <?php echo $form->error($model, 'password'); ?>
            </div>
            <?php echo $form->labelEx($model, 'Password Baru', array('class' => 'control-label col-sm-2')); ?>
            <div class="col-lg-4">
				<?php echo $form->passwordField($model, 'repeat_password', array('class'=>'form-control','placeholder'=>'Password Baru (Ulang)')); ?>
                <?php echo $form->error($model, 'repeat_password'); ?>
            </div>
        </div>
		<div class="form-group row">
            <?php echo $form->labelEx($model, 'Nomor hp', array('class' => 'control-label col-sm-2')); ?>
            <div class="col-lg-4">
                <?php echo $form->textField($model, 'nohp', array('maxlength' => 20, 'class' => 'form-control', 'placeholder' => 'No. HP')); ?>
                <?php echo $form->error($model, 'nohp'); ?>
            </div>
            <?php echo $form->labelEx($model, 'E-mail', array('class' => 'control-label col-sm-2')); ?>
            <div class="col-lg-4">
                <?php echo $form->textField($model, 'email', array('maxlength' => 50, 'class' => 'form-control', 'placeholder' => 'E-mail')); ?>
                <?php echo $form->error($model, 'email'); ?>
            </div>
        </div>
		<div class="form-group row">
            <?php echo $form->labelEx($model, 'Gambar', array('class' => 'control-label col-sm-2')); ?>
            <div class="col-lg-10">
                <?php echo $form->fileField($model, 'picture', array('maxlength' => 50, 'class' => 'form-control')); ?>
                <?php echo $form->error($model, 'picture'); ?>
            </div>
        </div>
		<div class="col-lg-12">
            <br/><br/>
            <?php echo CHtml::submitButton($model->isNewRecord ? 'Tambah' : 'Update', array('class' => 'btn btn-primary')); ?>
            <button type="button" class="btn btn-inverse" onclick="window.location.href='<?php echo CController::createUrl('user/admin'); ?>';">Cancel</button>
        </div>
        <?php $this->endWidget(); ?>
    </div><!-- form -->
</div></div></div>
</div>

<script type="text/javascript">
	$("#User_aksesid").select2({ containerCssClass: "myFont" });
</script>
<?php
$ismode = "add";
if (!$model->isNewRecord) {
    $ismode = "edit";
}
?>

<script type="text/javascript">
	$(document).ready(function () {
        loadAkses();
		loadPegawai(true);
		
		$('#' + '<?php echo CHtml::activeId($model, 'password') ?>').val('');
		$('#' + '<?php echo CHtml::activeId($model, 'repeat_password') ?>').val('');
    });
	
	function loadAkses() {
        $.ajax({
            url: "<?php echo CController::createUrl('user/loadakses') ?>",
            type: 'POST',
            data: {},
            success: function (data) {
                $('#<?php echo CHtml::activeId($model, 'aksesid') ?>').html(data);
                $('#' + '<?php echo CHtml::activeId($model, 'aksesid') ?>').select2().select2('val', '');
                $('#' + '<?php echo CHtml::activeId($model, 'aksesid') ?>').select2().select2('val', '<?php echo $model->aksesid; ?>');
            	
			},
            error: function (jqXHR, status, err) {
                //alert(err);
            }
        });
    }
	
	function loadPegawai(p_awal) {
        var v_aksesid = '';
		if (p_awal) {
			v_aksesid = '<?php echo $model->aksesid; ?>';
		}
		else {
			v_aksesid = $('#' + '<?php echo CHtml::activeId($model, 'aksesid') ?>').select2().select2('val');
		}
		$.ajax({
            url: "<?php echo CController::createUrl('user/loadpegawai') ?>",
            type: 'POST',
            data: { aksesid : v_aksesid },
            success: function (data) {
                $('#<?php echo CHtml::activeId($model, 'pegawaiid') ?>').html(data);
                $('#' + '<?php echo CHtml::activeId($model, 'pegawaiid') ?>').select2().select2('val', '');
                $('#' + '<?php echo CHtml::activeId($model, 'pegawaiid') ?>').select2().select2('val', '<?php echo $model->pegawaiid; ?>');
            },
            error: function (jqXHR, status, err) {
                //alert(err);
            }
        });
    }
</script>

protected/views/user/admin.php
<?php
/* @var $this UserController */
/* @var $model UserInfo */

Yii::import('ext.select2.Select2');
?>

<div class="row page-titles">
    <div class="col-md-5 align-self-center">
        <h4 class="text-themecolor">Data User</h4>
    </div>
    <div class="col-md-7 align-self-center text-right">
        <div class="d-flex justify-content-end align-items-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="<?php echo $this->createUrl('site/index'); ?>">Home</a></li>
                <li class="breadcrumb-item active">Data User</li>
            </ol>
			<button type="button" onclick='js:document.location.href="<?php echo $this->createUrl('user/create'); ?>"' class="btn btn-info d-none d-lg-block m-l-15"><i class="fa fa-plus-circle"></i> Tambah User</button>
        </div>
    </div>
</div>

<div class="clearfix"></div>
<div class="row">	
<div class="table-responsive" style="">
	<div class="card"><div class="card-body">
	<div class="form-group" id="" style="padding-right:15px;">
		<div class="row form-group">
			<div class="col-lg-12">
			    <?php 
					echo Select2::activeDropDownList($model, 'aksesid', array('' => ''), array(
                        'prompt' => 'PILIH HAK AKSES',
                        'class' => 'col-lg-12', 'style' => 'padding:0px','selected' => 'selected'
                    ));
				?>
			</div>
        </div>
		<div class="row form-group">
			<div class="col-lg-12"> 
                <?php echo CHtml::textField('searchtext','',array('size' => 60, 'maxlength' => 90, 'class' => 'form-control', 'placeholder' => 'Pencarian')); ?>
            </div>
        </div>
    </div>
    <?php
    $this->widget('zii.widgets.grid.CGridView', array(
        'id' => 'user-grid',
        'itemsCssClass' => 'table table-hover color-table info-table',
        // 'filter' => $model,
        'dataProvider' => $dataProvider,
        'ajaxUrl' => $this->createUrl('user/admin'),
        'pager' => array(
//            'prevPageLabel' => CHtml::tag('i', array('class' => 'fa fa-angle-double-left')),
//            'nextPageLabel' => CHtml::tag('i', array('class' => 'fa fa-angle-double-right')),
            'header' => 'User',
            'cssFile' => false,
            'htmlOptions' => array(
                'class' => 'pagination pagination-lg',
            ),
        ),
//        'dataProvider' => $model->search(),
        'columns' => array(
            // 'id',
            array(
                'header' => 'Grup',
                'name' => 'grupship_id',
                'type' => 'raw',
                'htmlOptions' => array('style' => 'font-size:15px;'),
                'value' => function($data) {
		            return $data['aksesnama'];
		        },
            ),
            array(
                'header' => 'Username',
                'name' => 'usernameship_id',
                'type' => 'raw',
                'htmlOptions' => array('style' => 'font-size:15px;'),
                'value' => function($data) {
		            return $data['username'];
		        },
            ),
            array(
                'header' => 'Nama',
                'name' => 'namaship_id',
                'type' => 'raw',
                'htmlOptions' => array('style' => 'font-size:15px;'),
                'value' => function($data) {
		            return $data['nama'];
		        },
            ),
            array(
                'template' => '{update}{delete}',
                'class' => 'CButtonColumn',
                'htmlOptions' => array('width' => 90, 'style' => 'text-align: center;'),
                'buttons' => array(
					'update' => array(
                        'url' => 'Yii::app()->createUrl("/user/update", array("userid"=>$data["userid"]))',
                        'visible' => '(!Yii::app()->user->getprivileges("edit", "3") && !Yii::app()->user->isSuperadmin())?0:1',
                    ),
                    'delete' => array(
                        'url' => 'Yii::app()->createUrl("/user/delete", array("userid"=>$data["userid"]))',
                        'visible' => '(!Yii::app()->user->getprivileges ("del", "3") && !Yii::app()->user->isSuperadmin())?0:1',
                    ),
                ),
            ),
        ),
    ));
    ?>
</div></div></div></div>
<script>
    function loadAkses() {
        $.ajax({
            url: "<?php echo CController::createUrl('user/loadakses') ?>",
            type: 'POST',
            data: {isall:'true'},
            success: function (data) {
                $('#<?php echo CHtml::activeId($model, 'aksesid') ?>').val('');
                $('#<?php echo CHtml::activeId($model, 'aksesid') ?>').html(data);
				if ("<?php echo $model->aksesid; ?>"!="")
                	$('#<?php echo CHtml::activeId($model, 'aksesid') ?>').select2().select2('val', "<?php echo $model->aksesid; ?>");
            },
            error: function (jqXHR, status, err) {
                //alert(err);
            }
        });
    }
	function tambahData() {
        js:document.location.href="<?php echo CController::createUrl('user/create') ?>/aksesid/"+$('#<?php echo CHtml::activeId($model, 'aksesid') ?>').val();
    }
	$(document).ready(function () {
        loadAkses();
		$('#searchtext').keyup(function(e){
			if(e.keyCode == 13)
		    {
				$.fn.yiiGridView.update('user-grid', {
					//data: $(this).serialize()
					data: {searchtext:$('#searchtext').val(),filteraksesid: $('#<?php echo CHtml::activeId($model, 'aksesid') ?>').val()},
				});
				return false;
			}
		});
		$('#<?php echo CHtml::activeId($model, 'aksesid') ?>').change(function(e){
			$.fn.yiiGridView.update('user-grid', {
				//data: $(this).serialize()
				data: {searchtext:$('#searchtext').val(),filteraksesid: $('#<?php echo CHtml::activeId($model, 'aksesid') ?>').val()},
			});
			return false;
		});
    });
</script>

protected/views/user/create.php
<?php
/* @var $this UserController */
/* @var $model User */

?>
<div class="row page-titles">
    <div class="col-md-5 align-self-center">
        <h4 class="text-themecolor">Tambah User</h4>
    </div>
    <div class="col-md-7 align-self-center text-right">
        <div class="d-flex justify-content-end align-items-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="<?php echo $this->createUrl('user/admin'); ?>">Data User</a></li>
                <li class="breadcrumb-item active">Tambah User</li>
            </ol>
        </div>
    </div>
</div>
<div class="clearfix"></div>

<?php echo $this->renderPartial('_form', array('model' => $model)); ?>

protected/views/user/index.php
<?php
/* @var $this UserController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Members',
);

$this->menu=array(
	array('label'=>'Create User', 'url'=>array('create')),
	array('label'=>'Manage User', 'url'=>array('admin')),
);
?>

<h1>Members</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/views/user/update.php
<?php
/* @var $this UserController */
/* @var $model User */

$this->breadcrumbs = array(
    'User' => array('admin'),
    'Ubah User',
);
?>


<div class="row page-titles">
    <div class="col-md-5 align-self-center">
        <h4 class="text-themecolor">Ubah User</h4>
    </div>
    <div class="col-md-7 align-self-center text-right">
        <div class="d-flex justify-content-end align-items-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="<?php echo $this->createUrl('user/admin'); ?>">Data User</a></li>
                <li class="breadcrumb-item active">Ubah User</li>
            </ol>
        </div>
    </div>
</div>
<div class="clearfix"></div>

<?php echo $this->renderPartial('_form', array('model' => $model)); ?>